name: Dev for Java-App CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/reusable_workflows.yaml
    with:
      image-name: 'fadel8/repo_1'
      environment: 'dev' 
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWD: ${{ secrets.PASSWD }}