name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/reusable.yml
    with:
      image-name: 'my-docker-image'
      environment: 'production' # Must match the GitHub Environment name if using Environment Secrets
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWD: ${{ secrets.PASSWD }}