name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/reusable_workflows.yaml
    with:
      image-name: 'fadel8/repo_1'
      environment: 'prod' # Must match the GitHub Environment name if using Environment Secrets
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWD: ${{ secrets.PASSWD }}