name: first workflow

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: fadel
      run: |
         echo ${{ vars.Identity }} 
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: fadel
      run: |
         echo ${{ vars.Identity }}       
