name: reusable_workflows

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

      environment:
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:

    - name: echo environment
      run: echo ${{ vars.ENVIRO_NAME }}

    - name: Get Source Code
      uses: actions/checkout@v7
      with:
        fetch-depth: '0'

    - name: Setup java v11
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build Java App
      run: mvn package install -DskipTests

    - name: Test Java App
      run: mvn test

    - name: Build Docker Image
      run: docker build -t ${{ inputs.image-name }}:v${{ github.run_number }} .

    - name: Login to Dockerhub
      run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWD }}

    - name: Push Docker Image
      run: docker push ${{ inputs.image-name }}:v${{ github.run_number }}

    - name: Get CD Repo
      uses: actions/checkout@v7
      with:
        Repository: https://github.com/mohhamedfadel8-lgtm/Java-App-CD.git
        path: cdRepo

    - name: Update Image Tag for CD
      run: |
        sed -i "s#.*image: .*#        image: ${{ inputs.image-name }}:v${{ github.run_number }}" cdRepo/deployment.yaml

    - name: Commit and Push Changes
      run: |
        cd cdRepo
        git config user.name "github-actions"
        git cionfig user.enail "github-actions@github.com"

        git add .
        git commit -m "Update Image Tag for CD"
        git push
