name: Test for Java-App CI

on:
  workflow_dispatch:

concurrency:
   group: 'java'
   cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/reusable_workflows.yaml
    with:
      image-name: "fadel8/repo_1"
      environment: "test"